### ISSUE TITLE
Import doesn't work in Blender 4.0

### ISSUE THREAD

**Issue by jesterKing** [jesterKing/import_3dm#109]
Importing of 3dm files in Blender 4.0 fails due to changed API to Principled BSDF.

**Comment by pattysm05** [comment]
hello, any chance this will be fixed in the coming future? thank you!

**Comment by jonemansons** [comment]
that would be amazing :)

**Comment by SpaceArchitecture** [comment]
Looks like this project is dead, might need to correct it ourselves
