### ISSUE TITLE
Update to rhino3dm 8.0.1

### ISSUE THREAD

**Issue by jesterKing** [jesterKing/import_3dm#110]
A new version of rhino3dm has been released. This is based on OpenNURBS of Rhino 8.

rhino3dm 8.0.1 provides access to RenderContent, which should make it easier to import materials as they are in Rhino - create the same (or very similar) shader graphs as RhinoCycles does.

**Comment by KeithSloan** [comment]
Okay made a start on exporter [B-Spline curves](https://forum.freecad.org/viewtopic.php?p=749032#p749032)

[https://github.com/KeithSloan/ImportExport_3DM
![Rotation_Sweep](https://github.com/jesterKing/import_3dm/assets/2291247/2eb8158e-2324-4cb1-bf02-a811b851723a)
](url)

**Comment by chenpaner** [comment]
Where？
