### ISSUE TITLE
doesn't work on linux

### ISSUE THREAD

**Issue by abderrahimokhnache** [jesterKing/import_3dm#112]
**Is your feature request related to a problem? Please describe.**

i couldn't use this addon on linux

**Describe the solution you'd like**

either you guys add a pack for linux or someone explain how to do it if it's already possible

**Comment by githubbbie** [comment]
Hi, the mac os x package worked for me on Linux.

That should be noted when making the packages, just generate mac packages intel and tag with linux.

I did not test this on ARM, as I have an intel-based computer.

BEST!

**Comment by jesterKing** [comment]
Please try the linux builds I added for v0.0.12.

I checked they work on Linux Mint 21.03 with Blender 4.1
