### ISSUE TITLE
Trouble installing on Mac

### ISSUE THREAD

**Issue by KeithSloan** [jesterKing/import_3dm#117]
When I download the ZIP-file on my Mac it is not automatically extracted - only when I click on it in either the download window of the browser, or directly in Finder. So don't do that.

1. Download the arm version of the package if you use the arm version of Blender, otherwise the Intel version
1. Install add-on, attempt to enable. Enabling will fail
2. Restart Blender
3. Go to add-ons, enable add-on.

In video format: https://youtu.be/C4g1K0fDmfw

_Originally posted by @jesterKing in https://github.com/jesterKing/import_3dm/issues/115#issuecomment-2096387597_
    
    Sorry but NO.

On my Mac the zip file was automatically unzipped, I did find that there is a Safari option to disable this but
setting the option and redownloading makes no difference.

I tried following Video but does not work, if I type in Rhinoceros, nothing is found.
If I click install and find the zip file in downloads and install then I get the same as I originally reporter.

Quitting Blender and restarting makes no difference

**Comment by KeithSloan** [comment]
Mac Intel zip

![Image 07-05-2024 at 06 08](https://github.com/jesterKing/import_3dm/assets/2291247/0152aae1-6741-4114-86bc-250521854485)

[system-info.txt](https://github.com/jesterKing/import_3dm/files/15229669/system-info.txt)

**Comment by jesterKing** [comment]
if you still have problems running the add-on try this:

1. install latest version
1. open up a terminal
1. `cd` into `~/Library/Library Support/Blender/4.1/scripts/addons/modules/rhino3dm`
1. run `sudo xattr -rd com.apple.quarantine *`
1. run Blender and see if it now enables correctly
