### ISSUE TITLE
Version of add-on for Blender 2.79 (Blender 2.7x)

### ISSUE THREAD

**Issue by Symbian9** [jesterKing/import_3dm#12]
Is there such add-on for Blender 2.7x?

If no, then, please, make `import_3dm` for Blender 2.79 too!

**Comment by jesterKing** [comment]
Hi @Symbian9,

at the moment I haven't planned for pre-2.8x, as the `rhino3dm.py` module itself is also still quite a bit in flux. That said, I gladly accept contributions that make this add-on compatible with 2.79 as well.

If time permits I might also give a go at that, but help here would be much appreciated.

**Comment by jesterKing** [comment]
With Blender already being at 3.0 I don't think it makes sense to try backport this anymore.

**Comment by Symbian9** [comment]
> With Blender already being at 3.0 I don't think it makes sense to try backport this anymore.

It make sence as Blender 3.0 does not work on older PC, while Blender 2.79 is suitable even on 10+ year-old laptops with integrated GPU.

Please, reopen.
