### ISSUE TITLE
Error importing Subd geometry

### ISSUE THREAD

**Issue by jingzhe-00** [jesterKing/import_3dm#122]
The add-on seems to not support importing Subd geometry made in rhino to blender. Upon hitting import, there is an error message which pops up. See screenshot for error message:

**Screenshots**
![Error message when importing subd](https://github.com/user-attachments/assets/b5dc6c01-e1da-4304-a207-4dd77eb74d65)
**Desktop:**
 - OS: Windows
 - Blender v4.1.1

**Comment by jesterKing** [comment]
Looks like in 4.1 `use_auto_smooth` has been removed.
