### ISSUE TITLE
About exporting obj format in Rhino 8

### ISSUE THREAD

**Issue by chenpaner** [jesterKing/import_3dm#124]
Hello, jester King.
     I'm so sorry I'm asking a question here that has nothing to do with your plugin, but I don't know how to contact you and ask questions about exporting obj format in Rhino 8, I'm the author of Link To Rhino this plugin. When I tested exporting a mesh in OBJ format in Rhino 8, a separate object mesh did not automatically weld the vertices, I posted a report  [here](https://discourse.mcneel.com/t/rhino-8-export-obj-vertexwelding-does-not-work/168488/3), but so far (Rhino 8 SR10
(8.10.2422 6.13001, 2024-08-13)) so far still did not solve this problem, I am not sure if you are the official programmer of Rhino, if you can help test whether it is a bug or my export method problem!
Please close this question when you read this! 
Thanks

**Comment by jesterKing** [comment]
@chenpaner you can at-mention me on the discourse forum with `@nathanletwory`. I am closing this thread so you can repeat notify me on discourse and we can continue from there.
