### ISSUE TITLE
Color Attribute input

### ISSUE THREAD

**Issue by grahamwheaton** [jesterKing/import_3dm#125]
Hello!,

Would it be possible to extract the color information from the .3dm file and add it as a blender attribute on import?

I have been sent a .3dm file that has color information (I'm not a Rhino user, so downloaded a trial to check).

When I import the 3dm using this addon it has no color attributes. But if I do nothing in Rhino but export as a .gltf it comes into Blender with them. ( I then separate the mesh up via geometry nodes, using the col attribute as a filter)

Ideally I would like a solution that means I don't need Rhino.

Not sure if this is possible? :)

Thanks

**Comment by jesterKing** [comment]
Yes, it is possible. I'm working on a patch for that.
