### ISSUE TITLE
Set scale in import settings

### ISSUE THREAD

**Issue by Ztreem** [jesterKing/import_3dm#14]
When importing a model from Rhino that is made in millimeters it comes into Blender 1000 times larger than expected. I suppose it's because of Blender using meters as default. 
So an option to set the scale in the import options would be nice.

**Comment by joel-putnam** [comment]
I am currently working this out here. Thoughts comments welcome. 

https://github.com/joel-putnam/import_3dm/tree/Units

**Comment by jesterKing** [comment]
#24 implemented this
