### ISSUE TITLE
Does this works for for apple?

### ISSUE THREAD

**Issue by disignore** [jesterKing/import_3dm#25]
Cannot install on Mac Blender 2.80? Is it functional only for Win?

**Comment by jesterKing** [comment]
I develop the importer mainly on the Mac. It should work.

What error(s) do you get?

**Comment by disignore** [comment]
It says that the modules are installed, but the add-on doesn't shows even after restart.

**Comment by jesterKing** [comment]
Builds prior to 2.79 aren't supported.

Make sure that rhino3dm is seen by Blender 2.80:

- start Blender 2.80
- switch to Scripting
- in the python console type: `import rhino3dm`

Do you get any error?

**Comment by jesterKing** [comment]
I've added instructions to install `rhino3dm.py` so that Blender 2.80 sees it.
