### ISSUE TITLE
Re-import of objects should be allowed to ignore Rhino material assignments.

### ISSUE THREAD

**Issue by jesterKing** [jesterKing/import_3dm#27]
**re-import of objects**
Upon re-import of a file that has been modified in Rhino it'd be useful if objects don't get materials reassigned. Texturing and material creation has often already been done in Blender, while objects are otherwise further modified in Rhino and re-imported.

**option to maintain existing material links**
Upon import provide an option that allows to maintain material assignments in the Blender file. That means not overwriting with whatever assignment comes from the Rhino file.

**Comment by tsvilans** [comment]
Solved in #29

**Comment by jesterKing** [comment]
#29 is now merged
