### ISSUE TITLE
Error on Win10 Blender 2.8

### ISSUE THREAD

**Issue by LadyRover** [jesterKing/import_3dm#30]
Hi,

I am trying to switch from Vray for Rhino to Blender 2.8 with Eevee. Modelling will continue in Rhino, so I do appreciate the efforts to add 3dm import.
Still I get the attached error when trying to import one of my Rhino files. Any ideas whats wrong?
Can I fix this? I'm purely a user and am not programming or Python savy...

Thanks.

![3DM Import Error](https://user-images.githubusercontent.com/45069608/63419672-7f3b8b00-c405-11e9-9ceb-6fdb60825fe5.jpg)

**Comment by tsvilans** [comment]
Hi @LadyRover you need to update `rhino3dm` to the latest version.

**Comment by LadyRover** [comment]
Hey, thanks for the quick answer. Where can I find that? I used this one:
https://github.com/jesterKing/import_3dm/releases/tag/0.0.3

**Comment by tsvilans** [comment]
> Hey, thanks for the quick answer. Where can I find that? I used this one:
> https://github.com/jesterKing/import_3dm/releases/tag/0.0.3

@LadyRover That is the Blender add-on. It depends on `rhino3dm` which is a different package.

**Comment by LadyRover** [comment]
My Rhino is on the latest release as far as I can see...

**Comment by jesterKing** [comment]
Please follow the installation instructions on the top page for this repository.

FWIW, Rhino 6 (and Rhino WIP 7) has the Cycles engine integrated as the Raytraced viewport mode. If you don't need the intricaties of the Blender material editor and compositor you should be able to stay entirely within Rhino to do your rendering.

**Comment by LadyRover** [comment]
Hey Jester,

thanks, but Blender has many more possibilities which I need to be able to use. 
Particles, moving objects, animations and the like. So I would definetly want to use Blender for rendering. Eevee looks also promising.
Still, Rhino is definetly my preferred modeler at this moment in time.
As Vray for Rhino keeps throwing issues at its users (such as changing the material definitions without conversion method for existing materials) I am seriously considering this switch.

Thats the very reason why I'd love this plugin to work.

Regarding installation. As far as I can see I did follow the instructions. Blender 2.8 is new installed, Python 3.7.1 is installed, I did install as described:

Open a cmd.exe (start > run > cmd.exe)
install rhino3dm.py by typing in the command prompt: pip3.7 install --user rhino3dm
Get the correct zip file from https://github.com/jesterKing/import_3dm/releases/latest (the one with import_3dm in the name)
Start Blender 2.80
In top menu press Edit > User Preferences...
Select the section Add-ons
In the bottom of that window select Install add-on from file...
Browse to where you saved the zip file, select it and press the Install add-on from file button in the top right of the file browser
Done. Probably a good idea to restart Blender.

I'll reinstall Python once more, maybe that helps? I am unclear on this:  "...have the installer add Python 3.7 to your PATH as well. Make sure pip gets installed (using the defaults from the first button, together with the checkbox for adding to PATH should get that set up)..."

**Comment by LadyRover** [comment]
Actually reinstalled Python (just downloaded the newest version 3.7.4) and used the PATH installation & pip thing too.

When I type I get an error. Do I need to change "--user" to a path pointing to my rhino.exe? :
>>> pip3.7 install --user rhino3dm
  File "<stdin>", line 1
    pip3.7 install --user rhino3dm
         ^
SyntaxError: invalid syntax
>>>

**Comment by tsvilans** [comment]
@LadyRover This may be a bit misleading, since Blender comes with its own Python installation. If you can't get `pip` to work using Blender's Python, try the following:

- Try running `pip install --upgrade rhino3dm` from the command line.
- Copy the `rhino3dm` folder from your system's Python `site-packages` folder (probably something like `C:\Program Files\Python37\Lib\site-packages`) to your Blender `modules` folder (probably something like `C:\Users\<your_name>\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\modules`).
- Restart Blender.

**Comment by LadyRover** [comment]
Hmmm.

When I ran pip install --upgrade rhino3dm it finished. Now when I go to:
C:\Users\das3Dstudio\AppData\Local\Programs\Python\Python37\Lib\site-packages
There is no Rhino3dm folder in there.

Rerunning "pip install --upgrade rhino3dm" gives me:
Requirement already up-to-date: rhino3dm in c:\users\das3dstudio\appdata\local\programs\python\python37-32\lib\site-packages (0.5.0)

*I'm confused*

**Comment by tsvilans** [comment]
> C:\Users\das3Dstudio\AppData\Local\Programs\Python\Python37\Lib\site-packages

> Requirement already up-to-date: rhino3dm in c:\users\das3dstudio\appdata\local\programs\python\python37-32\lib\site-packages (0.5.0)

There's a difference: `Python27` vs `python37-32`

**Comment by LadyRover** [comment]
Which means I probably installed Python in two versions. Or could that happen when installing Blender 2.8. I am on a 64bit system
Shall I deinstall Blender and Python completly and retry?
Probably without manually installing Python, because, as you say Blender comes with its own Python version?

**Comment by tsvilans** [comment]
No, the Blender Python is self-contained.

**Comment by LadyRover** [comment]
Which means only install Blender?

**Comment by tsvilans** [comment]
> Which means only install Blender and remove Python before?

No, your system Python is independent from Blender's.

### Check if you have `pip`
1. Look in `C:\Program Files\Blender Foundation\Blender 2.8\2.80\python\`
2. If there is a `Scripts` folder and it contains `pip.exe`, then yes. If not, then install `pip`.

### Install `pip`
1. Open the command line with admin privileges (Run... -> "cmd.exe")
2. Type in `cd "C:\Program Files\Blender Foundation\Blender 2.8\2.80\python\bin"`
3. Type in `python ensurepip` **or** `"C:\Program Files\Blender Foundation\Blender 2.8\2.80\python\bin\python" ensurepip`
4. If that doesn't work, download `get-pip.py` [here](https://bootstrap.pypa.io/get-pip.py).
5. Type in  `"C:\Program Files\Blender Foundation\Blender 2.8\2.80\python\bin\python" "<path-to-get-pip.py>"` where `<path-to-get-pip.py>` is wherever you saved `get-pip.py`. Remember the double quotes.

### Install / upgrade `rhino3dm` for Blender
1. Still in the command prompt, type in `"C:\Program Files\Blender Foundation\Blender 2.8\2.80\python\Scripts\pip" install --upgrade rhino3dm`

These instructions should ensure that your Blender Python is used to install `pip` and `rhino3dm`.

**Comment by LadyRover** [comment]
Still stuck. Downloaded Pip.
Than ran:

"C:\Program Files\Blender Foundation\Blender\2.80\python\bin\python" "<E:\03 DOWNLOAD\get-pip.py>"

I'm sure its a stupid mistake though ;-)

**Comment by jesterKing** [comment]
Hey @LadyRover , I finally managed to merge #29 by @tsvilans to master. I released an updated version of the add-on as v0.0.4. This particular version should handle installing the rhino3dm dependency (and pip) completely magically for you.

Please download and install it. Let me know if activating that updated add-on now works for you.

**Comment by LadyRover** [comment]
Hi Jester. 

Great, seems to install, I get a green notification at the bottom of the screen.
Hook on the add on is there, so it should be visible under Import.
Still I have no import filter showing up (in Version 3 I had this showing but got the error mentioned in posting 1.

This despite the fact that I reinstalled version 2.80 of Blender and deinstalled the "non Blender" Python.

Thanks for your efforts!!

What is a bit strange too is that when I reinstalled Blender 2.80 (I checked after deinstallation that there are no more folders relating to version 2.80 in Program Files) the add-ons are still there.
Despite cleaning out the registry and restarting.

Not sure if that is important there is also still a Blender 2.79 Version on the machine.

**Comment by LadyRover** [comment]
Actually just repeated the Blender installation and manually removed the plugin before I reinstalled Blender & the plugin.

Plugin installed (Bottom green confirmation).

But when I try to activate I get an error. See screenshot.
![3DM Import Error2](https://user-images.githubusercontent.com/45069608/63501250-9a70ce00-c4cb-11e9-997c-ec0e3e2e6880.jpg)

**Comment by jesterKing** [comment]
Hmm, I did my testing using the official zip, not installer. You may have to start Blender as elevated user to be able to write to the install location.

I'll make a change to also install `pip` in a normal user-writable location.

**Comment by tsvilans** [comment]
@LadyRover Sounds like you need to start Blender with admin privileges.

**Comment by LadyRover** [comment]
I just tried it while running Blender with administrator privileges (had the Add-On manually removed before).
Upon install I get the green line that it installed. But when I want to set the "hook" to enable it I still got an error.

**But after restarting Blender than once more, I could set the hook & *HORRAY* its working!!!!!

Goood stuff! Thank you so much!!!**

One more question, in Rhino with Vray I assigned materials by layers. Would there be a way to have all parts of one layer to come into Blender as sort of group to which I could assign a material? Not sure, I'm fairly new to Blender.

**Comment by jesterKing** [comment]
You should still be able to assign materials by layer in Rhino. Upon import objects will get the layer material they were on in Rhino.

AFAIK there is no layer material concept in Blender yet - not sure if the `overrides` project in Blender will eventuallyt offer something similar.

Anyway, now that you are up and running I'm going to close this issue. For further discussion please use the discourse.mcneel.com forum to start new topics. You can tag me (`@nathanletwory`) directly there to get my attention.
