### ISSUE TITLE
Verify installation instructions in `readme`

### ISSUE THREAD

**Issue by tsvilans** [jesterKing/import_3dm#31]
**Describe the bug**
Blender comes with its own Python installation. The `readme` indicates that the system Python installation can be used for installing `rhino3dm`.

**Expected behavior**
1. If PR #29 goes through, the `readme` should change to reflect this.
2. Otherwise, detailed instructions for installing `pip` for Blender Python, and updating `rhino3dm` using Blender Python should be added.

**Comment by jesterKing** [comment]
I have merged #29 with updated instructions for install on Windows.
