### ISSUE TITLE
Polycurve has no segments

### ISSUE THREAD

**Issue by tsvilans** [jesterKing/import_3dm#33]
**Describe the bug**
Can't find a way to file this issue in `rhino3dm`... A Polycurve object has a `SpanCount` property to see how many segments it has, but no corresponding `Segments` property to access all the subcurves. This needs to be exposed in `rhino3dm` to enable processing Polycurves.

**Comment by jesterKing** [comment]
Hi @tsvilans,

I've reported this as https://mcneel.myjetbrains.com/youtrack/issue/RH3DM-34

**Comment by jesterKing** [comment]
Hi @tsvilans,

`rhino3dm` 0.6.0 should have access to the segments in. Can you test please?

**Comment by tsvilans** [comment]
@jesterKing Works!

Now just need to figure out how to do arc conversions... Blender doesn't have native arc types.

`arc.ToNurbsCurve()` gives some pretty funky results.

**Comment by tsvilans** [comment]
All good here. See PR #37

**Comment by jesterKing** [comment]
Cool, I'll check #37 soon
