### ISSUE TITLE
Option for importing objects with assigned layer material

### ISSUE THREAD

**Issue by SerLinkzero** [jesterKing/import_3dm#40]
## Issue

Currently all objects with "Use Layer Material" property in Rhino are imported assigned a material with the layer's name and display color.

## Request

In architecture and urban design modeling, it is a common practice to differentiate object materials by Rhino layers. It would be very helpful if the importer provide an option to assign corresponding Layer Material to the objects instead of the display color material as described above.

## Example

Rhino layer `Wood` has `#0000ff` as display color, and is assigned a material `Walnut`, and all objects in this layer have the material property of "Use Layer Material".

**Current behavior**: In the imported scene, objects in collection `Wood` have a material named `Wood`, the diffuse color of which is `#0000ff`.

**Desired behavior**: Objects in collection `Wood` should be assigned material `Walnut`.

**Comment by tsvilans** [comment]
@jesterKing @joel-putnam @lfertig I've made a branch to address this. What I'm a bit stuck on is whether to replace the material import with render materials completely, or to keep the option of converting the display material to Blender materials instead... Is the display color / material necessary for anything?

Otherwise, I could set the Blender object display color to the Rhino display color, if it needs to be kept. Thoughts?

**Comment by joel-putnam** [comment]
I think the layer display color was to just have something. I believe when this was first done the library had very limited to no access to Rhinos RDK. I think there is/was an issue where we where not getting a material id back if the object is set to "use layer" but It was some time ago. Ideally we would use the objects assigned materiel and if its "by layer" we would now get that id as well.

**Comment by joel-putnam** [comment]
On a side note it might be nice to set the object display color to the rhino display color. I know that I have a custom colors.txt file I use to organize the way I use color for layers and objects within Rhino. This would be nice to have it come through as I have a fairly standard workflow for element types such as walls slabs glass etc. Viewport parity would be nice.

**Comment by tsvilans** [comment]
Ok, great, then I will finish up and submit a PR :)

All of those things are now available so it should be fine.

**Comment by tsvilans** [comment]
That's a good shout. Ok, so the display color will be converted to the Blender object color.

**Comment by tsvilans** [comment]
This is handled in #47 and is just waiting for a second check before merging.
