### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by romio82** [jesterKing/import_3dm#5]
Not completely sure but this could be a typo:

https://github.com/jesterKing/import_3dm/blob/01914fe4ff0b28fb2346a98c5bf9b089acf9a332/import_3dm.py#L25

Shouldn't line 25 read:
idblock['rhname'] = name
At least that's how the Rhino name block is called in line 40..

Is there a better way to report issues like this? Would I open a PR for this?
Or would I rather collect more stuff and then request a collective pull after some time?

**Comment by tsvilans** [comment]
This is the correct way to raise issues :)

**Comment by jesterKing** [comment]
@romio82 yes, that is a typo indeed. Since the rhname key isn't used yet it didn't matter, but better to have it fixed. Feel free to create a PR for this!

**Comment by jesterKing** [comment]
You should be able to reference this issue in your PR, which then nicely ties it into this. Good for code forensics/archeology later on (:
