### ISSUE TITLE
handle exceptions in utils.get_iddata

### ISSUE THREAD

**Issue by lfertig** [jesterKing/import_3dm#55]
**Describe the bug**
Some objects are currently not id-tagged (views for example). If you use utils.get_iddata() with objectdata=None and the search loop hits an untagged and unnamed item before finding the actual id you're looking for, it raises an error (blender cant create new objects with objectdata=None).

**To Reproduce**
1. make sure you have a testfile with e.g. views in it
2. to provoke the error: run get_iddata() with a uuid thats not in the file, base=context.blend_data.objects and objectdata=None
3. loop hits the untagged view before finding anything and causes an error because of objectdata=None

**Expected behavior**
*utils.get_iddata should handle unwanted cases
(*all items that have an uuid in rhino should have one assigned in blender, see Issue #57)

**Comment by tsvilans** [comment]
This is also a little bit of a problem with `utils.get_iddate`... doing `bpy.data.objects.new("Name", None)` creates an Empty object (good) but then it throws an error with materials, because `bpy.data.materials.new()` only takes 1 argument...

**Comment by jesterKing** [comment]
I believe that with the latest code data creation and id tagging is a lot more robust.

If exception cases pop up please create new issues for those.
