### ISSUE TITLE
Import curves

### ISSUE THREAD

**Issue by jesterKing** [jesterKing/import_3dm#6]
Blender supports Bezier, NURBS and Polyline curves

**Comment by tsvilans** [comment]
FWIW, I've implemented something similar in the `SpeckleBlender` add-on: https://github.com/speckleworks/SpeckleBlender/blob/master/bpy_speckle/convert/from_speckle/curve.py

Once I have some time I will try to port this over.

There will also need to be a bit of faffing around to get Rhino NURBS curves to be represented correctly as Blender NURBS curves... From initial testing, there seem to be pretty big differences in how they are represented.

**Comment by jesterKing** [comment]
That would be very cool @tsvilans . Curves are a bit beyond me, so it would be a great deal if we can get curves supported in the add-on!

**Comment by tsvilans** [comment]
@jesterKing This is now solved / underway. Specific issues with curve import could be raised as separate issues maybe?

**Comment by jesterKing** [comment]
#34 and #37 implement much of the curves, closing this.

Thanks @tsvilans !
