### ISSUE TITLE
blender 2.8 Unable to load import_3dm v0.0.6

### ISSUE THREAD

**Issue by hahajaja** [jesterKing/import_3dm#61]
![image](https://user-images.githubusercontent.com/23209894/68800713-94872500-0695-11ea-8de3-a2a1b2053a6b.png)

**Comment by Eryamatrix** [comment]
you should go to the release page to download zip file, https://github.com/jesterKing/import_3dm/releases

**Comment by hahajaja** [comment]
![image](https://user-images.githubusercontent.com/23209894/68890450-e0030700-0759-11ea-9d83-04dc78cbfaa7.png)
Thanks for your reply, I have the same problem in the release page download.

**Comment by jesterKing** [comment]
You'll need to update your rhino3dm module.

**Comment by hahajaja** [comment]
thanks

**Comment by bunterWolf** [comment]
Can you share how you did it.? 
I guess I don't finde the right pip version or module location. Its confusion.. :)

**Comment by PaulBouisset** [comment]
I have a similar issue. I run on MacOS 10.14, I follow the instructions for the MacOS preparation.
I run Blender 2.8, I downloaded import_3dm v0.0.6 for the release page but the import option does not show up in my "Import" menu on Blender. 
I also got no error message during installation.

**Comment by nickatanaz** [comment]
Same issue on Windows 10 with Blender 2.80 and 2.81.
Updates?

**Comment by gavinmetzler** [comment]
On Windows 10, I run command prompt as administrator, then
cd\Program Files\Blender Foundation\Blender 2.81\2.81\python\bin
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python.exe get-pip.py
..\Scripts\pip.exe install rhino3dm 

then of course download zip from https://github.com/jesterKing/import_3dm/releases and in Blender install from zip as usual.

**Comment by JohnBelding** [comment]
I just tried the install using gavinmetsler's method and got an error:

After running curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
ERROR:
Failed to create the file get-pip.py: Permission denied

Since I can't install rhino3dm, I can't install the Blender addon.

Any help would be appreciated.

**Comment by tsvilans** [comment]
Sounds like you need admin privileges to run that. 

If this doesn't work, in the Blender Python console, try running this, line by line:
```
import os, subprocess
modulespath = os.path.normpath(os.path.join(bpy.utils.script_path_user(),"addons","modules"))
res = subprocess.run([bpy.app.binary_path_python, "-m", "pip", "install", "--upgrade", "-t", "{}".format(modulespath), "rhino3dm"])
```

Bear in mind, if it's enabled, you need to disable the add-on and reboot Blender, otherwise it won't let you update `rhino3dm`.

**Comment by chrbaumeister** [comment]
I followed gavinmetzler's instructions and installed the module. It worked. In the blender python console I can access that module. 

**But** I can't acivate the PlugIn in my preferences. Installed the latest release in Blender 2.82

Same Error as mentioned above: "... no attribute named PolyCurve..."

**Comment by tsvilans** [comment]
@chrbaumeister You need to update from the latest code in the master branch.
Please see the possible solution in #62 . This seems to work for most cases.

**Comment by chrbaumeister** [comment]
Great! Got it. Thanks for your help!

**Comment by gauthamrahul** [comment]
@tsvilans can you please share that #62 addon...coz it is not available online...only problem here is the polycurve error... it would be great if you help me sharing that #62 addon.

**Comment by gauthamrahul** [comment]
> @chrbaumeister You need to update from the latest code in the master branch.
> Please see the possible solution in #62 . This seems to work for most cases.

can you please share #62 addon

**Comment by tsvilans** [comment]
@gauthamrahul Just download it:

`https://github.com/jesterKing/import_3dm -> Clone or download -> Download ZIP`

**Comment by gauthamrahul** [comment]
> https://github.com/jesterKing/import_3dm -> Clone or download -> Download ZIP

sorry bro couldn't download it

**Comment by gauthamrahul** [comment]
> @gauthamrahul Just download it:
> https://github.com/jesterKing/import_3dm -> Clone or download -> Download ZIP

downloaded and installd but again this polycurve is nt soled

**Comment by tsvilans** [comment]
Can you show the error message? Print screen of the Blender console or copypasta.
