### ISSUE TITLE
Can't enable addon

### ISSUE THREAD

**Issue by mond-cz** [jesterKing/import_3dm#62]
I followed pip installation for Mac users with success, but enabling the add-on fails.
It seems to me `rhino3dm` can't be installed.

Terminal log from pip installation:
[installation_pip.txt](https://github.com/jesterKing/import_3dm/files/3941443/installation_pip.txt)

Terminal log running Blender from terminal with rhino3dm installation process:
[installation_rhino3dm.txt](https://github.com/jesterKing/import_3dm/files/3941424/installation_rhino3dm.txt)

Sorry, I'm not a command line user, so I just noticed to consider update pip 19.0.3 to 19.3.1 (that's what I thought I did right now with your instructions) and try to install rhino3dm manually. 

First I tried to update pip from home dir with 
`pip install --upgrade pip`

... but "command not found". So I wanted to try install rhino3dm manually 
`pip3 install --upgrade --target /Users/filip/Library/Application Support/Blender/2.81/scripts/addons/modules rhino3dm`

... but it failed too - like if the path exists? If "path" means directory, so Yes -exists, I can see empty "module" folder it that directory. In this log Terminal mentions even I use pip 9.0.3 ?!
[installation_rhino3dm_manually.txt](https://github.com/jesterKing/import_3dm/files/3941522/installation_rhino3dm_manually.txt)

Any advice or direction to hunt issue?
Thank you for help.

**Screenshots**
![Screen Shot 2019-12-09 at 19 36 50](https://user-images.githubusercontent.com/649050/70466506-93de8480-1ac3-11ea-8132-8628b50610f2.png)

**Desktop (please complete the following information):**
 - OS: X 10.12.6
 - Blender 2.81a / 2.82alpha

**Additional context**

**Comment by iuviene** [comment]
Add on installs without any errors but won't appear in add-ons afterwards nor is it available in the import or export menus.  

Blender v2.81.16 on macOS 10.14.6

**Comment by copyme** [comment]
@iuviene please run `pip3 install rhino3dm --user` it takes a bit of time but it should solve the problem. In general, the add-on should not try to install rhino3dm itself because in my case it caused more problems than it should. This should be a per-installtion step.

**Comment by synxroform** [comment]
Should i run pip3 from Blender's python distribution, or from globally installed python.

**Comment by tsvilans** [comment]
Blender's Python distro.

**Comment by synxroform** [comment]
Just did it, but nothing happens. No errors, typing "import rhino3dm as 3dm" in blender's python console works normally. Try "center = 3dm.Point3d(1,2,3)" - OK. Just realised how it's great, in the past days you had to program using pywin3d COM library.

**Comment by synxroform** [comment]
I have rhino3m 0.11.0, requirements.txt say rhino3dm>=0.1.4. Maybe some features were dropped.

**Comment by tsvilans** [comment]
Try typing in the following in the Blender Python console:
```
modulespath = os.path.normpath(os.path.join(bpy.utils.script_path_user(),"addons","modules"))
import subprocess
res = subprocess.run([bpy.app.binary_path_python, "-m", "pip", "install", "-t", "{}".format(modulespath), "rhino3dm"])
```

**Comment by synxroform** [comment]
Oh my ###, just realized i install it from master-branch zip file. Now it works.

**Comment by mond-cz** [comment]
I wanted to try it again.
When I start from scratch … following instructions (packed with addon) for mac users:

```
cd /Users/filip/Downloads/Blender\ 2.app/Contents/Resources/2.82/python

rm -rf ./lib/python3.7/site-packages/pip*

./bin/python3.7m ./lib/python3.7/ensurepip

ls ./bin

./bin/pip3.7 install --upgrade --target ~/Library/Application\ Support/Blender/2.82/scripts/addons/modules rhino3dm
```

Beginning seems to work, “pip3” and “pip3.7” lands in the directory, but last command (install or update rhino3dm.py) doesnt seem to work. It starts installation, but it ends with **error code 1** 

```
Command ""/Users/filip/Downloads/Blender 2.app/Contents/Resources/2.82/python/bin/python3.7m" -u -c "import setuptools, tokenize;__file__='/private/var/folders/jr/tfyh0hcn2kz477q0hpd108hm0000gn/T/pip-install-1ozh4aes/rhino3dm/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/jr/tfyh0hcn2kz477q0hpd108hm0000gn/T/pip-record-iq0y0zpq/install-record.txt --single-version-externally-managed --compile --home=/private/var/folders/jr/tfyh0hcn2kz477q0hpd108hm0000gn/T/pip-target-av7v9bc8" failed with error code 1 in /private/var/folders/jr/tfyh0hcn2kz477q0hpd108hm0000gn/T/pip-install-1ozh4aes/rhino3dm/
```

with a note
"You are using pip version 19.0.3, however version 20.0.2 is available."
"You should consider upgrading via the 'pip install --upgrade pip' command."

BTW - this update command is not working, but that is not the main issue I guess
Also I tried @copyme answer “pip3 install rhino3dm --user” ends with the same error

There is not module “rhino3dm” in folder “modules” in path ~/Library/Application\ Support/Blender/2.82/scripts/addons/modules

**Comment by tsvilans** [comment]
@mond-cz Try running the commands I wrote above in the Blender Python console.

**Comment by mond-cz** [comment]
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
NameError: name 'os' is not defined

**Comment by tsvilans** [comment]
Before the first line, add
`import os`

**Comment by mond-cz** [comment]
**@tsvilans OMG :) installed _rhino3dm-0.11.0_! Add-on enabled! Thank you so much.**

So working way is to follow addon's instructions and instead of last step installation of module _rhino3dm_ via Terminal is used blender's console with your code ...

```
import os
modulespath = os.path.normpath(os.path.join(bpy.utils.script_path_user(),"addons","modules"))
import subprocess
res = subprocess.run([bpy.app.binary_path_python, "-m", "pip", "install", "-t", "{}".format(modulespath), "rhino3dm"])
```

Any reason why Terminal can't reach that point?
Is it something specific to my mac or instructions should be corrected?

BTW any tip to update `pip` 19 to 20? Terminal says use `pip install --upgrade pip`, but it results in `Command not found`. Do I'm running it from a wrong directory or its a command issue?

Anyway thanks again, that I would not be able manage without you.

**Comment by tsvilans** [comment]
It's not that important to update `pip` but you can do it the same way:

```
import subprocess
res = subprocess.run([bpy.app.binary_path_python, "-m", "pip", "install", "--upgrade", "pip"])
```
You might need to run Blender with admin privileges for this one, though.

Regarding the addon, yes, we are still trying to find the best way which also works for all platforms. The way I showed you looks promising, so that might be implemented in the next release.

**Comment by mond-cz** [comment]
Thank you for help and improvements :)

(btw - I have admin privilege for the comp)
