### ISSUE TITLE
Does not work with rhino3dm v0.10.0

### ISSUE THREAD

**Issue by maxnowack** [jesterKing/import_3dm#64]
The plugin does not work with the latest version of rhino3m. It works if I downgrade to v0.9.0.

![image](https://user-images.githubusercontent.com/186073/73758841-6cc2cd00-476b-11ea-9959-b982f5c46da2.png)

**Comment by tsvilans** [comment]
This bug has been fixed in #67. Please try the latest version and see if it is solved.
