### ISSUE TITLE
Is possible to preserve UVs?

### ISSUE THREAD

**Issue by louzelig** [jesterKing/import_3dm#74]
When import my rhino files into blender,  UV mappings are gone.
If I want to preserve UV maps, I need to export my files to OBJ in Rhino and then import it to Blender, but in that case, my layers are gone.
Is there any way to preserve my UVs? Thanks!!!

**Comment by lfertig** [comment]
It is partially implemented, but not public yet. Also, at the moment it only supports a single mapping, multiple channels will not be possible for a while, as it is missing some internal functionality. I'll post here once it is online, unfortunately i can't tell right now when this will be..

**Comment by ScienceofSpock** [comment]
This is what I'm waiting for as well.

**Comment by jesterKing** [comment]
The UV import is available in v0.0.9

**Comment by ScienceofSpock** [comment]
Awesome, thanks for this!
