### ISSUE TITLE
Traceback error while enabling

### ISSUE THREAD

**Issue by TomReedInspiration** [jesterKing/import_3dm#75]
Error appears while turning it on
![image](https://user-images.githubusercontent.com/44962234/90518223-236a2600-e16f-11ea-9245-7916fe242eda.png)

**To Reproduce**
1. Install from a ZIP
2. Try to mark in preferences

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Blender 2.83

**Comment by jesterKing** [comment]
The cause for the error is no longer the issue - automated rhino3dm install or update has been completely removed.
