### ISSUE TITLE
Blender 2.9 ?

### ISSUE THREAD

**Issue by alextugin** [jesterKing/import_3dm#78]
Problem with Blender 2.9. Add on  is installed but not available option import!

**Comment by jesterKing** [comment]
Did you install from https://github.com/jesterKing/import_3dm/releases/latest ?

**Comment by alextugin** [comment]
Yes! Install add on, and pip import3dm

**Comment by jesterKing** [comment]
On what platform are you?

**Comment by alextugin** [comment]
Mac OS

**Comment by jesterKing** [comment]
You should only install the Zip file for MacOS from the releases page. You don't have to use pip, as the zip contains all the code and dependencies needed.

**Comment by alextugin** [comment]
Look please this screen rec https://youtu.be/_PNUV0SjFWA

**Comment by alextugin** [comment]
What do you think about this?

**Comment by jesterKing** [comment]
Not sure, I see this:

https://youtu.be/3y7lTTejRrY

**Comment by alextugin** [comment]
Thanks for help !

**Comment by alextugin** [comment]
I don't know how, but now all ready and installed! This is magic! Thank you
