### ISSUE TITLE
Crashes Blender 2.91 and 2.92 - Windows 7, 64-bit

### ISSUE THREAD

**Issue by maxim1967** [jesterKing/import_3dm#84]
**Describe the bug**
Does not work in Blender 2.91 and 2.92!!! Running the program causes the Blender to close.

**Comment by tsvilans** [comment]
Can you run Blender from the command line and post what it says when it crashes?

**Comment by maxim1967** [comment]
The problem is due to Windows 7 x64. On Windows 10 x64 everything works. Alas, I do not know how to run the Blender from the command line, so I will not be able to send what the program writes when it crashes.

**Comment by tsvilans** [comment]
See: https://superuser.com/questions/494538/how-do-i-open-a-program-via-the-command-prompt-in-windows-8

1. Press `Windows + R`
2. type in `cmd`
3. Blender is typically in `C:/Program Files/Blender Foundation/Blender 2.92/blender.exe` so just type that into the command prompt and take a screenshot of whatever appears there when it crashes.

**Comment by maxim1967** [comment]
A computer with Windows 7 at work will be able to take a picture only tomorrow. Thank you for the hint on how to do this.

**Comment by maxim1967** [comment]
![Снимок](https://user-images.githubusercontent.com/62519357/113971387-5a499500-9841-11eb-8bab-b3ccb348ba88.PNG)
For 2.92 Windows 7 x64 as well.

**Comment by jesterKing** [comment]
The code for `rhino3dm` is compiled for Windows 8.1 and up only. `Rhinoceros 3D` no longer supports Windows 7, and as a result also the `rhino3dm` version doesn't support Windows 7.
