### ISSUE TITLE
Activation error in Blender 2.93

### ISSUE THREAD

**Issue by maxim1967** [jesterKing/import_3dm#85]
**Describe the bug**
Activation error in Blender 2.93

![Снимок](https://user-images.githubusercontent.com/62519357/115036658-646d3280-9ed6-11eb-973a-cb28788c4c22.JPG)

**Comment by kittrick** [comment]
I'm getting the same error on Mac OS 11.2.3 with Blender 2.93.

**Comment by kittrick** [comment]
I can verify that the plugin seems to work on on OSX 11.2.3 with Blender 2.92

**Comment by studio-travis** [comment]
Hi
I also can not see addon active in Blender 2.93. Please check
Thank

**Comment by Qign** [comment]
I'm getting the same error

**Comment by usefulthink** [comment]
This seems to have to do with the bundled python not having `pip` (package installer) properly installed. 
I was able install the addon by doing the following:
 - open a terminal
 - change into the installation-path of the bundled python (on macOS that would be `cd /Applications/Blender.app/Contents/Resources/2.93/python`) 
 - run the command `./bin/python -m pip install -U pip` to upgrade and install the bundled pip
 - activate the addon

A fix for this might be to change the way pip is invoked when installing the depedencies (i.e. don't expect the binary to be there and use `python -m pip` instead).

**Comment by jesterKing** [comment]
Handling this in #88
