### ISSUE TITLE
Add Support for blender 2.93 and above,as 2.93 release is nearing

### ISSUE THREAD

**Issue by arcdipesh** [jesterKing/import_3dm#88]
as current version does work for 2.92 but doesnt work for 2.93 and above please do update to support newer version.

**Comment by jesterKing** [comment]
I've added a ZIP for Blender 2.93 on the Mac. Note that this is Mac Intel only, so you'll need to use the Mac Intel build of Blender.

I'll update the Windows version soon, too.

**Comment by jesterKing** [comment]
I've added now also a ZIP archive for Blender 2.93 on Windows.
