### ISSUE TITLE
Mac M1 Support?

### ISSUE THREAD

**Issue by monksalve** [jesterKing/import_3dm#89]
Awesome add-on. Works great.

Are there any plans to support the M1 chips?

**Comment by jesterKing** [comment]
Not in the near-near future, but once we get M1 builds of the `rhino3dm` package we'll be able to use it on such hardware.

**Comment by jesterKing** [comment]
Until there is the apple silicon version of `rhino3dm` the intel build should work with the intel build of Blender on M1

**Comment by jesterKing** [comment]
I have finally managed to get `rhino3dm`  versions for Apple Silicon. I have uploaded bundled versions of v0.0.10 to the release page https://github.com/jesterKing/import_3dm/releases/tag/0.0.10
