### ISSUE TITLE
Doesn't install in blender 2.93.6

### ISSUE THREAD

**Issue by mjoe67886** [jesterKing/import_3dm#90]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Linux]
 - Blender version/build

**Additional context**

**Comment by mjoe67886** [comment]
Sorry don't have time to write this but just try and install it in blender 2.93.6 and you will see what I mean

**Comment by jesterKing** [comment]
I have just now installed v0.0.8 in Blender 2.93.6 and Blender  3.0-daily on Windows, and it worked just fine.

Can you maybe explain a bit more what errors you see, and what operating system you are using?

**Comment by jesterKing** [comment]
v0.0.9 installs in both 2.93.6 and 3.0.0
