### ISSUE TITLE
Rhino 7 Import

### ISSUE THREAD

**Issue by kitaedesigns** [jesterKing/import_3dm#93]
Rhino 7 files don't seem to import correctly or at all. Rhino 5 files are the most consistent.

**Comment by saloarhussain** [comment]
Yes.. same problem not importing the file

**Comment by jesterKing** [comment]
Please share a file that does not import correctly.

Note that linked block instances are currently not supported.

**Comment by jesterKing** [comment]
In case you needed SubD support that is now available with v0.0.10 of the add-on

![kuva](https://user-images.githubusercontent.com/87916/159634481-fd428ca0-75d2-4f68-9d10-48b16455fa64.png)

No further response was given so closing this topic.
