### ISSUE TITLE
Blender for Mac

### ISSUE THREAD

**Issue by GeorgPopp** [jesterKing/import_3dm#95]
Hi there, 

Does the Plug-In also run for Blender on macOS?
I cannot get it to work. 

Best, 
Georg

**Comment by jesterKing** [comment]
It works on Intel MacOS, but not yet on Apple Silicon. I'm waiting for proper builds of the module `rhino3dm`.

**Comment by jesterKing** [comment]
Duplicate of #89

**Comment by jesterKing** [comment]
FWIW using the Intel binary on M1 works fine even in Blender 3.2 alpha builds

Here I imported a house I modeled in Rhino 7

<img width="1055" alt="kuva" src="https://user-images.githubusercontent.com/87916/159220768-42d98592-533f-42dc-b91d-41665a880b15.png">
