### ISSUE TITLE
Activation Issue

### ISSUE THREAD

**Issue by JPCunning** [jesterKing/import_3dm#96]
I know this has shown up in other threads, but I have not been able to resolve it in Blender 3.1. I am getting this error when I try to activate the Add-on: 

![pastedImage](https://user-images.githubusercontent.com/5833363/157976743-db51b7c1-4c83-4d70-aefb-ec34766d3439.png)

**Comment by jesterKing** [comment]
I need to rerelease the add-on with `rhino3dm` compiled against the correct Python version that is used by Blender 3.1

**Comment by JPCunning** [comment]
OK Great, thank  you for the response! Is there a timeline on that by chance?

**Comment by MichaelArchBlend** [comment]
Bump

**Comment by jesterKing** [comment]
Please try v0.0.10. Take care to download the correct package for your Blender version
