### ISSUE TITLE
The add-on doesnt seem to install

### ISSUE THREAD

**Issue by algoknows** [jesterKing/import_3dm#97]
![image](https://user-images.githubusercontent.com/102029674/159247684-a8a400aa-d123-43e7-ac5e-93627871686b.png)
Was trying to install add-on on Blender 3.0 (Windows 11) and ran into this problem. 

Also tried to run script, didnt help though
![image](https://user-images.githubusercontent.com/102029674/159248091-34c0a9ca-3098-4dd6-ad90-a0601ba58b17.png)

Looking forward to your reply

**Comment by algoknows** [comment]
And yes, installed from https://github.com/jesterKing/import_3dm/releases/tag/0.0.10

**Comment by jesterKing** [comment]
I have noticed that for some reason you need to restart Blender after installing the add-on. Enabling `import_3dm` will work then.

I don't know why that happens, though.
