### ISSUE TITLE
import rhino3dm

### ISSUE THREAD

**Issue by GeorgPopp** [jesterKing/import_3dm#98]
Hi there, 

I managed to import rhino3dm library to have access in blender for windows. But it was a long road for me to achieve this and i think i didn't do it the easiest way. And now I cannot manage to do it for Mac (Imac with Intel)

I would really appreciate if you could provide a manual which explains how to do this for windows and mac for the latest blender version. I think this is a main issue where it fails for so many users of this plug-in. 

Best, 
Georg

**Comment by jesterKing** [comment]
1) download the version of `import_3dm` appropriate for your Blender version from the release page https://github.com/jesterKing/import_3dm/releases/tag/0.0.10
2) install the add-on in Blender
3) restart Blender
4) enable the add-on
